import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:ns_transport/providers/salary_provider.dart';
import 'package:ns_transport/widgets/app_drawer.dart';
import 'package:ns_transport/widgets/empty_state.dart';
import 'package:ns_transport/utils/formatters.dart';

class DriverSalaryScreen extends ConsumerStatefulWidget {
  const DriverSalaryScreen({super.key});

  @override
  ConsumerState<DriverSalaryScreen> createState() => _DriverSalaryScreenState();
}

class _DriverSalaryScreenState extends ConsumerState<DriverSalaryScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(salaryProvider.notifier).loadSalaries();
    });
  }

  Future<void> _refresh() async {
    await ref.read(salaryProvider.notifier).loadSalaries();
  }

  @override
  Widget build(BuildContext context) {
    final salariesAsync = ref.watch(salaryProvider);
    final primaryColor = const Color(0xFF1565C0);

    return Scaffold(
      appBar: AppBar(
        title: Text('My Salary', style: GoogleFonts.inter(fontWeight: FontWeight.w600, color: Colors.white)),
        backgroundColor: primaryColor,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      drawer: const AppDrawer(),
      body: RefreshIndicator(
        onRefresh: _refresh,
        color: primaryColor,
        child: salariesAsync.when(
          data: (salaries) {
            if (salaries.isEmpty) {
              return const Center(
                child: SingleChildScrollView(
                  physics: AlwaysScrollableScrollPhysics(),
                  child: EmptyState(
                    icon: Icons.account_balance_wallet_outlined,
                    title: 'No Earnings Data',
                    message: 'Your salary records will appear here once generated by the owner.',
                  ),
                ),
              );
            }

            // Calculations
            double outstandingNetPayable = 0;
            double totalAdvances = 0;
            double totalBaseSalary = 0;

            for (var sal in salaries) {
              outstandingNetPayable += sal.netSalary;
              totalAdvances += sal.advances;
              totalBaseSalary += sal.baseSalary;
            }

            return ListView(
              physics: const AlwaysScrollableScrollPhysics(),
              padding: const EdgeInsets.all(16.0),
              children: [
                // Summary Panel
                Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      colors: [primaryColor, const Color(0xFF1E88E5)],
                      begin: Alignment.topLeft,
                      end: Alignment.bottomRight,
                    ),
                    borderRadius: BorderRadius.circular(16),
                    boxShadow: [
                      BoxShadow(
                        color: primaryColor.withValues(alpha: 0.3),
                        blurRadius: 10,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Column(
                    children: [
                      Text(
                        'OUTSTANDING NET PAYABLE',
                        style: GoogleFonts.inter(
                          color: Colors.white70,
                          fontSize: 12,
                          fontWeight: FontWeight.w600,
                          letterSpacing: 1.2,
                        ),
                      ),
                      const SizedBox(height: 6),
                      Text(
                        Formatters.formatCurrency(outstandingNetPayable),
                        style: GoogleFonts.inter(
                          color: Colors.white,
                          fontSize: 28,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 20),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceAround,
                        children: [
                          _buildMiniStat(
                            'Base Earnings',
                            Formatters.formatCurrency(totalBaseSalary, compact: true),
                          ),
                          Container(width: 1, height: 30, color: Colors.white24),
                          _buildMiniStat(
                            'Total Advances',
                            Formatters.formatCurrency(totalAdvances, compact: true),
                          ),
                        ],
                      )
                    ],
                  ),
                ),
                
                const SizedBox(height: 28),
                
                Text(
                  'Monthly Payment History',
                  style: GoogleFonts.inter(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Colors.black87,
                  ),
                ),
                const SizedBox(height: 12),
                
                ListView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: salaries.length,
                  itemBuilder: (context, index) {
                    final salary = salaries[index];
                    final dateStr = DateFormat('MMMM yyyy').format(
                      DateTime(salary.year, salary.month),
                    );

                    final isPaid = salary.status == 'paid';

                    return Card(
                      margin: const EdgeInsets.only(bottom: 12),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                        side: BorderSide(color: Colors.grey.shade200),
                      ),
                      elevation: 1,
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  dateStr,
                                  style: GoogleFonts.inter(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16,
                                  ),
                                ),
                                Container(
                                  padding: const EdgeInsets.symmetric(
                                    horizontal: 8,
                                    vertical: 4,
                                  ),
                                  decoration: BoxDecoration(
                                    color: isPaid
                                        ? Colors.green.shade50
                                        : Colors.orange.shade50,
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                  child: Text(
                                    salary.status.toUpperCase(),
                                    style: GoogleFonts.inter(
                                      fontSize: 11,
                                      fontWeight: FontWeight.bold,
                                      color: isPaid
                                          ? Colors.green.shade700
                                          : Colors.orange.shade800,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                            const Divider(height: 24),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                _buildDetailRowItem(
                                  'Base Salary',
                                  Formatters.formatCurrency(salary.baseSalary),
                                ),
                                _buildDetailRowItem(
                                  'Advances Deducted',
                                  Formatters.formatCurrency(salary.advances),
                                ),
                                _buildDetailRowItem(
                                  'Net Paid',
                                  Formatters.formatCurrency(salary.paidAmount),
                                ),
                              ],
                            ),
                            const SizedBox(height: 12),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  'Remaining Balance:',
                                  style: GoogleFonts.inter(
                                    fontSize: 13,
                                    color: Colors.grey.shade600,
                                  ),
                                ),
                                Text(
                                  Formatters.formatCurrency(salary.netSalary),
                                  style: GoogleFonts.inter(
                                    fontSize: 14,
                                    fontWeight: FontWeight.bold,
                                    color: isPaid ? Colors.green : Colors.red.shade700,
                                  ),
                                ),
                              ],
                            )
                          ],
                        ),
                      ),
                    );
                  },
                )
              ],
            );
          },
          loading: () => const Center(child: CircularProgressIndicator()),
          error: (err, stack) => Center(
            child: Text(
              'Error loading salary info: $err',
              style: GoogleFonts.inter(color: Colors.red),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildMiniStat(String label, String value) {
    return Column(
      children: [
        Text(
          value,
          style: GoogleFonts.inter(
            color: Colors.white,
            fontSize: 16,
            fontWeight: FontWeight.bold,
          ),
        ),
        Text(
          label,
          style: GoogleFonts.inter(
            color: Colors.white70,
            fontSize: 11,
          ),
        ),
      ],
    );
  }

  Widget _buildDetailRowItem(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 11,
            color: Colors.grey.shade600,
          ),
        ),
        const SizedBox(height: 2),
        Text(
          value,
          style: GoogleFonts.inter(
            fontSize: 14,
            fontWeight: FontWeight.w600,
            color: Colors.black87,
          ),
        ),
      ],
    );
  }
}
